#!/usr/bin/env python3
"""Render the Copilot agent files from the two persona files.

`agents/python-dev.md` and `agents/py-reviewer.md` are the only hand-written
copies. Copilot cannot read them from a plugin, and `npx skills add` installs
skill folders only, so rendered copies ship inside the py-intake skill at
`skills/py-intake/templates/copilot/*.agent.md`, and intake copies them into a
target repo's `.github/agents/`.

What rendering changes:
  - frontmatter keeps `name` and `description`, drops the Claude Code keys
    (model, effort, color, tools, initialPrompt), adds
    `include-custom-instructions: true` so the agent sees AGENTS.md
  - `${CLAUDE_PLUGIN_ROOT}/skills/py-intake` becomes `.agents/skills/py-intake`,
    where `npx skills add` installs the skill in the target repo
  - `agents/py-reviewer.md` becomes `.github/agents/py-reviewer.agent.md`
  - the persona's `initialPrompt` becomes a first line in the body, because
    Copilot agents have no initial prompt

Usage:
  python scripts/render_agents.py           # write the rendered files
  python scripts/render_agents.py --check   # exit 1 if they differ from what
                                            # would be written (CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = {
    ROOT / "agents" / "python-dev.md": ROOT / "skills/py-intake/templates/copilot/python-dev.agent.md",
    ROOT / "agents" / "py-reviewer.md": ROOT / "skills/py-intake/templates/copilot/py-reviewer.agent.md",
}
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
KEEP_KEYS = ("name", "description")
PATH_SUBS = (
    ("${CLAUDE_PLUGIN_ROOT}/skills/py-intake", ".agents/skills/py-intake"),
    ("`agents/py-reviewer.md`", "`.github/agents/py-reviewer.agent.md`"),
)


def render(source: Path) -> str:
    text = source.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise SystemExit(f"{source}: no frontmatter")
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    body = text[match.end():]
    for old, new in PATH_SUBS:
        body = body.replace(old, new)
    first_turn = fields.get("initialPrompt", "").strip('"')

    out = ["---"]
    for key in KEEP_KEYS:
        if key in fields:
            out.append(f"{key}: {fields[key]}")
    out.append("include-custom-instructions: true")
    out.append("---")
    out.append("")
    out.append(
        f"<!-- Generated by scripts/render_agents.py in fbhadha/py-dev from agents/{source.name}. "
        "Do not edit here; edit the source and re-render. -->"
    )
    out.append("")
    if first_turn:
        out.append(f"Your first turn, before anything else: {first_turn[0].lower() + first_turn[1:]}")
        out.append("")
    out.append(body.lstrip("\n"))
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    for source, target in SOURCES.items():
        rendered = render(source)
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if check:
            if current != rendered:
                stale.append(str(target.relative_to(ROOT)))
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
        print(f"wrote {target.relative_to(ROOT)}")
    if stale:
        print("RENDERED AGENTS ARE STALE; run python scripts/render_agents.py:")
        for path in stale:
            print(f"  - {path}")
        return 1
    if check:
        print("rendered agent files are current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
