#!/usr/bin/env python3
"""Render the Copilot agent files from the three Claude Code agent files.

`agents/python-dev.md`, `agents/py-reviewer.md` and `agents/py-eval.md` are the
only hand-written copies. Copilot CLI reads a plugin's agents from
`com.github.copilot/agents/` as `NAME.agent.md` with its own frontmatter, so
those are generated here and checked by CI, never edited by hand.

What rendering changes:
  - frontmatter keeps `name` and `description`, drops the Claude Code keys
    (model, effort, color, tools, initialPrompt, hooks) and adds the Copilot
    keys in RENDERED: python-dev is user-selected only
    (`disable-model-invocation: true`), py-reviewer and py-eval are
    model-dispatched only (`user-invocable: false`); py-eval also keeps its
    tool list as Copilot's aliases for Read and Write (`read`, `edit`)
  - `${CLAUDE_PLUGIN_ROOT}` becomes `${PLUGIN_ROOT}`, the name Copilot documents
  - `agents/<name>.md` becomes `com.github.copilot/agents/<name>.agent.md`
  - the persona's `initialPrompt` becomes the first line of the body, because
    Copilot agents have no initial prompt

Usage:
  python scripts/render_agents.py           # write the rendered files
  python scripts/render_agents.py --check   # exit 1 if they differ from what
                                            # would be written (CI)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "com.github.copilot" / "agents"
SOURCES = {
    ROOT / "agents" / "python-dev.md": OUT / "python-dev.agent.md",
    ROOT / "agents" / "py-reviewer.md": OUT / "py-reviewer.agent.md",
    ROOT / "agents" / "py-eval.md": OUT / "py-eval.agent.md",
}
RENDERED = {  # the Copilot frontmatter each agent gets: who may start it, the tools it keeps
    "python-dev.md": {"disable-model-invocation": "true"},
    "py-reviewer.md": {"user-invocable": "false"},
    "py-eval.md": {"user-invocable": "false", "tools": '["read", "edit"]'},
}
FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
KEEP_KEYS = ("name", "description")
PATH_SUBS = (
    ("${CLAUDE_PLUGIN_ROOT}", "${PLUGIN_ROOT}"),
    ("`agents/py-reviewer.md`", "`com.github.copilot/agents/py-reviewer.agent.md`"),
    ("`agents/py-eval.md`", "`com.github.copilot/agents/py-eval.agent.md`"),
)


def render(source: Path) -> str:
    text = source.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if not match:
        raise SystemExit(f"{source}: no frontmatter")
    fields: dict[str, str] = {}
    for line in match.group(1).splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip()
    body = text[match.end():]
    for old, new in PATH_SUBS:
        body = body.replace(old, new)
    first_turn = fields.get("initialPrompt", "").strip('"')

    out = ["---"]
    for key in KEEP_KEYS:
        if key in fields:
            out.append(f"{key}: {fields[key]}")
    for key, value in RENDERED[source.name].items():
        out.append(f"{key}: {value}")
    out.append("---")
    out.append("")
    out.append(
        f"<!-- Generated by scripts/render_agents.py from agents/{source.name}. "
        "Do not edit; edit the source and re-render. -->"
    )
    out.append("")
    if first_turn:
        out.append(f"Your first turn, before anything else: {first_turn[0].lower() + first_turn[1:]}")
        out.append("")
    out.append(body.lstrip("\n"))
    return "\n".join(out).rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    stale: list[str] = []
    for source, target in SOURCES.items():
        rendered = render(source)
        current = target.read_text(encoding="utf-8") if target.exists() else None
        if check:
            if current != rendered:
                stale.append(str(target.relative_to(ROOT)))
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered, encoding="utf-8")
        print(f"wrote {target.relative_to(ROOT)}")
    if stale:
        print("RENDERED AGENTS ARE STALE; run python scripts/render_agents.py:")
        for path in stale:
            print(f"  - {path}")
        return 1
    if check:
        print("rendered agent files are current")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
